- id: '1538681182328'
  alias: Home Assistant Shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: offline
      qos: 1
      retain: true
      topic: status/homeassistant
    service: mqtt.publish
- id: '1538715712827'
  alias: Enable Outlet when Rover is Home
  trigger:
  - entity_id: group.rover
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.teslacharger
    service: switch.turn_on
  - data:
      entity_id: light.garage
    service: light.turn_on
- id: '1538717746774'
  alias: Disable Outlet when Rover leaves Home
  trigger:
  - entity_id: group.rover
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: switch.teslacharger
    service: switch.turn_off
- id: '1538719850300'
  alias: Soil Moisture is Low
  trigger:
  - below: '15'
    entity_id: sensor.filtered_soil_moisture
    platform: numeric_state
  condition: []
  action:
  - data:
      brightness_pct: 80
      color_name: blue
      entity_id: light.gold_lamp
    service: light.turn_on
  - data:
      data:
        url: https://www.glousher.com:8123/lovelace/overview
      message: 'The moisture level is currently: {{ states.sensor.soilmoisture.state_with_unit
        }}'
      title: The Plant is Thirsty!
    service: notify.notify
- id: '1538720130028'
  alias: Set Gold Lamp to Relax when Soil Moisture is OK
  trigger:
  - above: '40'
    entity_id: sensor.soilmoisture
    platform: numeric_state
  condition:
  - condition: state
    entity_id: light.gold_lamp
    state: 'on'
  action:
  - data:
      brightness_pct: 50
      entity_id: light.gold_lamp
      profile: relax
    service: light.turn_on
- id: '1538743670093'
  alias: Do at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.bugzapper
    service: switch.turn_off
  - data:
      name: solarized-light
    service: frontend.set_theme
- id: '1538743708457'
  alias: Do at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.bugzapper
    service: switch.turn_on
  - data:
      name: solarized-dark
    service: frontend.set_theme
- id: '1538746855607'
  alias: Warning for Upcoming SSL Expiry
  trigger:
  - below: '10'
    entity_id: sensor.ssl_certificate_expiry
    platform: numeric_state
  condition: []
  action:
  - alias: ''
    data:
      message: The SSL certificate that is currently used for www.glousher.com will
        expire in less then {{ states.sensor.ssl_certificate_expiry.state_with_unit
        }} days. Please renew asap!
      title: SSL Certificate Expires in {{ states.sensor.ssl_certificate_expiry.state_with_unit
        }}
    service: persistent_notification.create
  - data:
      data:
        url: https://www.glousher.com:8123/lovelace/system
      message: The SSL certificate that is currently used for www.glousher.com will
        expire in less then {{ states.sensor.ssl_certificate_expiry.state_with_unit
        }} days. Please renew asap!
      title: SSL Certificate Expires in {{ states.sensor.ssl_certificate_expiry.state_with_unit
        }}
    service: notify.notify_jeffs_raster
- id: '1538747724448'
  alias: Daily Let's Encrypt Renewal
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_start
- id: '1539078291420'
  alias: HTML5 Notification Click Action - Open Door
  trigger:
  - event_data:
      action: open_door
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.garage
    service: light.toggle
- id: '1539110174578'
  alias: Home Assistant Start
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: switch.living_room_flux
    service: switch.turn_on
  - data:
      entity_id: switch.garage_flux
    service: switch.turn_on
  - data:
      entity_id: switch.kitchen_flux
    service: switch.turn_on
  - data:
      entity_id: switch.dining_flux
    service: switch.turn_on
- id: '1540154226330'
  alias: Stop charging Rover on a workday
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.tesla_model_3_5yj3e1ea8hf000718_charger_sensor
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: group.rover
    state: home
  action:
  - data:
      entity_id: switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
    service: switch.turn_off
- id: '1541340849898'
  alias: Stop charging Rover on a weekend/holiday
  trigger:
  - at: '15:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.tesla_model_3_5yj3e1ea8hf000718_charger_sensor
    state: 'on'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  - condition: state
    entity_id: group.rover
    state: home
  action:
  - data:
      entity_id: switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
    service: switch.turn_off
- id: '1542042353145'
  alias: Notify when Rovers is not at home and start charging
  trigger:
  - entity_id: binary_sensor.tesla_model_3_5yj3e1ea8hf000718_charger_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.rover
    state: not_home
  action:
  - data:
      data:
        url: https://www.glousher.com:8123/lovelace/rover
      message: It looks like rover is not at home and just started charging
      title: Rover Charging Started
    service: notify.notify_jeffs_raster
- id: '1542582264688'
  alias: Do a bit after Sunrise
  trigger:
  - event: sunrise
    offset: +02:00:00
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      name: default
    service: frontend.set_theme
- id: '1542882910962'
  alias: Turn garage light off again
  trigger:
  - entity_id: light.garage
    for: 00:10:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.garage
    service: light.turn_off
- id: '1547788214677'
  alias: Start Charging Rover
  trigger:
  - at: 04:00:00
    platform: time
  condition:
  - condition: state
    entity_id: group.rover
    state: home
  action:
  - data:
      entity_id: switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
    service: switch.turn_on
