homeassistant:
  name: Home # Name of the location where Home Assistant is running
  latitude: !secret home_lat # Location required to calculate the time the sun rises and sets
  longitude: !secret home_long
  elevation: !secret home_elev # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric # metric for Metric, imperial for Imperial
  time_zone: America/Toronto # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  customize: !include customize.yaml # Customization file, not sure why this is formatted differently from below

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 150
  - name: Tesla
    latitude: !secret tes_lat
    longitude: !secret tes_long
    radius: 200

recorder: # configure the connection to the external mySQL database, running as a docker container on a different host
  db_url: !secret db_url
  purge_keep_days: 365
  
influxdb: # configure the connection to the TICK stack, running as a docker container on a different host
  host: 192.168.1.51
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password

media_player: # configure basic control on the TV, unfortunatly it anly allows for power OFF (no power ON supported)
  - platform: samsungtv
    name: TV
    host: 192.168.1.30

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  
alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_user
  password: !secret alarm_pass
  code: !secret alarm_code

mqtt: # Configure LAN accessible MQTT server, running as a docker container on a different host
  broker: 192.168.1.51
  discovery: true
  discovery_prefix: homeassistant_autogen
  birth_message:
    topic: 'status/homeassistant'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'status/homeassistant'
    payload: 'offline'
    qos: 1
    retain: true

frontend: # Enables the frontend, all this work would be silly without it (there are no other instances of HassOS)
  themes:
    solarized-light:
        # Main colors
        primary-color: '#586e75'                                                        # Header
        accent-color: '#fdf6e3'                                                         # Accent color
        dark-primary-color: '#586e75'                                                   # Hyperlinks                                         
        light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
        # Text colors                                                                  
        primary-text-color: '#657b83'                                                   # Primary text colour, here is referencing dark-primary-color
        text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
        secondary-text-color: '#93a1a1'                                                 # For secondary titles in more info boxes etc.
        disabled-text-color: '#7F848E'                                                  # Disabled text colour
        label-badge-border-color: 'green'                                               # Label badge border, just a reference value   
        # Background colors                                                            
        primary-background-color: '#fdf6e3'                                             # Settings background
        secondary-background-color: '#eee8d5'                                           # Main card UI background  
        divider-color: 'rgba(0, 0, 0, .12)'                                             # Dividers
        # Table rows                                                                   
        table-row-background-color: '#fdf6e3'                                           # Table row
        table-row-alternative-background-color: '#eee8d5'                               # Table row alternative
        # Nav Menu                                                                   
        paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
        paper-listbox-background-color: 'var(--accent-color)'                           # Navigation menu background
        paper-grey-50: 'var(--primary-text-color)'                                   
        paper-grey-200: 'var(--accent-color)'                                           # Navigation menu selection
        # Paper card                                                               
        paper-card-header-color: 'var(--dark-primary-color)'                            # Card header text colour
        paper-card-background-color: 'var(--accent-color)'                              # Card background colour
        paper-dialog-background-color: '#fdf6e3'                                        # Card dialog background colour
        paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
        paper-item-icon-active-color: '#b58900'                                         # Icon color active
        paper-item-icon_-_color: 'green'           
        paper-item-selected_-_color: 'var(--accent-color)'
        paper-item-selected_-_background-color: '#cb4b16'                               # Popup item select                      
        paper-tabs-selection-bar-color: 'green'
        # Labels 
        label-badge-red: '#586e75'                                                      # References the brand colour label badge border
        label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
        label-badge-background-color: 'var(--accent-color)'                             # Same, but can also be set to transparent here
        # Switches
        paper-toggle-button-checked-button-color: '#268bd2'
        paper-toggle-button-checked-bar-color: 'var(--primary-color)'
        paper-toggle-button-checked-ink-color: '#268bd2'
        paper-toggle-button-unchecked-button-color: 'var(--secondary-background-color)'
        paper-toggle-button-unchecked-bar-color: 'var(--secondary-text-color)'
        paper-toggle-button-unchecked-ink-color: 'var(--secondary-background-color)'  
        # Sliders
        paper-slider-knob-color: 'var(--secondary-text-color)'
        paper-slider-knob-start-color: 'var(--secondary-text-color)'
        paper-slider-pin-color: 'var(--secondary-text-color)'
        paper-slider-active-color: 'var(--secondary-text-color)'
        paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
        paper-slider-secondary-color: 'var(--secondary-background-color)'
        paper-slider-disabled-active-color: 'var(--disabled-text-color)'
        paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
        # Google colors
        google-red-500: '#dc322f'
        google-green-500: '#859900'
        
    solarized-dark:
      primary-color: "#586e75"
      accent-color: "#002b36"
      dark-primary-color: "#93a1a1"
      light-primary-color: "var(--accent-color)"
      primary-text-color: "#839496"
      text-primary-color: "var(--primary-text-color)"
      secondary-text-color: "#586e75"
      disabled-text-color: "#7F848E"
      label-badge-border-color: "green"
      primary-background-color: "#002b36"
      secondary-background-color: "#073642"
      divider-color: "rgba(0, 0, 0, .12)"
      table-row-background-color: "#002b36"
      table-row-alternative-background-color: "#073642"
      paper-listbox-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--accent-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-grey-200: "var(--accent-color)"
      paper-card-header-color: "var(--dark-primary-color)"
      paper-card-background-color: "var(--accent-color)"
      paper-dialog-background-color: "#002b36"
      paper-item-icon-color: "var(--primary-text-color)"
      paper-item-icon-active-color: "#b58900"
      paper-item-icon_-_color: "#859900"
      paper-item-selected_-_color: "var(--accent-color)"
      paper-item-selected_-_background-color: "#cb4b16"
      paper-tabs-selection-bar-color: "#859900"
      label-badge-red: "#93a1a1"
      label-badge-text-color: "var(--primary-text-color)"
      label-badge-background-color: "var(--accent-color)"
      paper-toggle-button-checked-button-color: "#268bd2"
      paper-toggle-button-checked-bar-color: "var(--primary-color)"
      paper-toggle-button-checked-ink-color: "#268bd2"
      paper-toggle-button-unchecked-button-color: "var(--secondary-background-color)"
      paper-toggle-button-unchecked-bar-color: "var(--secondary-text-color)"
      paper-toggle-button-unchecked-ink-color: "var(--secondary-background-color)"
      paper-slider-knob-color: "var(--secondary-text-color)"
      paper-slider-knob-start-color: "var(--secondary-text-color)"
      paper-slider-pin-color: "var(--secondary-text-color)"
      paper-slider-active-color: "var(--secondary-text-color)"
      paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
      paper-slider-secondary-color: "var(--secondary-background-color)"
      paper-slider-disabled-active-color: "var(--disabled-text-color)"
      paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
      sidebar-selected-icon-color: 'var(--secondary-text-color)'
      sidebar-icon-color: 'var(--primary-text-color)'
      google-red-500: "#dc322f"
      google-green-500: "#859900"

config: # Enables configuration UI

http: # Configure url path, this is a Google Domains domain with the needed firewall settings at the NAT (OPNsense)
  base_url: https:/www.glousher.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater: # Optional, allows Home Assistant developers to focus on popular components. https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
  include_used_components: true

# Discover some devices automatically
discovery:
    
conversation: # Allows you to issue voice commands from the frontend in enabled browsers

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Weather

tesla: # Tesla car tracking
  username: !secret tesla_user
  password: !secret tesla_password

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_password
    
switch:
  - platform: wake_on_lan
    mac_address: "70:85:c2:4c:de:8f"
    name: Thunder
    host: 192.168.1.81
    
  - platform: flux
    name: Entryway Flux
    lights:
      - light.entryway
    disable_brightness_adjust: True
    mode: mired
    start_colortemp: 2237 #Relax color temperature
    sunset_colortemp: 2890 #Read color temperature
    stop_colortemp: 2237 #Relax color temperature

  - platform: flux
    name: Hallway Flux
    lights:
      - light.hallway
    disable_brightness_adjust: True
    mode: mired
    start_colortemp: 2237 #Relax color temperature
    sunset_colortemp: 2890 #Read color temperature
    stop_colortemp: 2237 #Relax color temperature

  - platform: flux
    name: Living Room Flux
    lights:
      - light.living_room
    disable_brightness_adjust: True
    mode: mired
    start_colortemp: 2237 #Relax color temperature
    sunset_colortemp: 2890 #Read color temperature
    stop_colortemp: 2237 #Relax color temperature

  - platform: flux
    name: Dancefloor Flux
    lights:
      - light.dancefloor
    disable_brightness_adjust: True
    mode: mired
    start_colortemp: 2237 #Relax color temperature
    sunset_colortemp: 2890 #Read color temperature
    stop_colortemp: 2237 #Relax color temperature

  - platform: flux
    name: Dining Flux
    lights:
      - light.dining
    disable_brightness_adjust: True
    mode: mired
    start_colortemp: 2237 #Relax color temperature
    sunset_colortemp: 2890 #Read color temperature
    stop_colortemp: 2237 #Relax color temperature

binary_sensor:
  - platform: iss
    show_on_map: false

  - platform: workday
    country: US
    province: CA
 
sensor:
  - platform: steam_online
    api_key: steam_api
    accounts:
      - 76561197993790475

  - platform: season
    type: astronomical

  - platform: filter
    name: "filtered soil moisture"
    entity_id: sensor.soilmoisture
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

  - platform: darksky
    name: Weather
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase

  - platform: cert_expiry
    host: www.glousher.com
    port: 8123
# moon 
  - platform: moon
# HassOS monitor
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /home
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: load_1m
      - type: network_in
        arg: 'enp2s1'
      - type: network_out
        arg: 'enp2s1'
      - type: processor_use
# System Uptime
  - platform: uptime
    unit_of_measurement: hours
# Dehumidifier Power Tracking
  - platform: template
    sensors:
      dehumidifier_watts:
        friendly_name: "Dehumidifier Power"
        unit_of_measurement: "w"
        value_template: "{{ states.switch.teslacharger.attributes.current_power_w }}"
     
plant:
 window:
   sensors:
     moisture: sensor.soilmoisture
     temperature: sensor.soiltemperature
     brightness: sensor.light
     
device_tracker:
  - platform: nmap_tracker
    hosts:
    - 192.168.1.31
    - 192.168.1.32
    - 192.168.1.33
    - 192.168.1.36
  - platform: google_maps
    username: !secret google_user_gh
    password: !secret google_password_gh
    track_new_devices: true

tts: # Text to speech
  - platform: google
  
shopping_list:

system_health:

default_config:

notify:
  - platform: html5
    name: notify
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender

cloud: # Cloud???

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
