title: Estates
views:
  - id: 0  # Automatically created id
    title: Home
    icon: mdi:home
    cards:
      - id: 961aa9b141b742558751a72d13f33864  # Automatically created id
        type: weather-forecast
        entity: weather.weather
      - id: d6ce7657e6a24af89470fea37c5ce8ee  # Automatically created id
        type: plant-status
        entity: plant.window
      - id: 69fd0431b8444b5d96e83e40c666f6e3  # Automatically created id
        type: entities
        title: all switches
        show_header_toggle: false
        entities:
          - switch.bugzapper
          - switch.flux
          - switch.thunder
      - id: 8f5df9b0db7d465a8dd6319660e876cd  # Automatically created id
        type: entities
        title: all lights
        show_header_toggle: true
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
      - id: 194a0c25bf234ad0adfa7b4e5825a632  # Automatically created id
        type: media-control
        entity: media_player.tv
  - id: rover
    title: Rover
    icon: mdi:car
    cards:
      - id:
        type: thermostat
        entity: climate.tesla_model_3_5yj3e1ea8hf000718_hvac_climate_system
      - id: 94a140513bf5430db35832e934828c15  # Automatically created id
        type: entities
        title: all locks
        show_header_toggle: true
        entities:
          - lock.tesla_model_3_5yj3e1ea8hf000718_door_lock
      - id: 
        type: entities
        title: all switches
        show_header_toggle: false
        entities:
          - switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
          - switch.tesla_model_3_5yj3e1ea8hf000718_maxrange_switch
          - switch.teslacharger
      - type: sensor
        entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
        name: Battery
        height: 75
        line_color: "#3498db"
  - id: system
    title: System
    icon: mdi:server
    cards:
      - id: 2ba63662d88a4c48b5cd846e9b81b8bf  # Automatically created id
        type: entities
        title: all scripts
        show_header_toggle: true
        entities:
          - script.1539135661190
      - id: 390b7eaf807646e885d38aa1b2035a99  # Automatically created id
        type: entities
        title: all automations
        show_header_toggle: false
        entities:
          - automation.daily_lets_encrypt_renewal
          - automation.disable_outlet_when_rover_leaves_home
          - automation.do_at_sunrise
          - automation.do_at_sunset
          - automation.enable_outlet_when_rover_is_home
          - automation.html5_notification_click_action__open_door
          - automation.home_assistant_shutdown
          - automation.home_assistant_start
          - automation.set_gold_lamp_to_relax_when_soil_moisture_is_ok
          - automation.stop_charging_rover
          - automation.turn_gold_lamp_blue_when_soil_moisture_is_low
          - automation.warning_for_upcoming_ssl_expirey