title: Estates
# Exclude entities from "Unused entities" view
excluded_entities:
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_locks
  - group.all_plants
  - group.all_scripts
  - group.all_switches
  - light.entertainment_area_1
  - device_tracker.tesla_model_3_5yj3e1ea8hf000718_location_tracker
  - device_tracker.b4e62ae90d29
  - device_tracker.404e36902186
  - device_tracker.android957114c2e834a0d6gloushercom
views:

  - id: overview
    title: Home Overview
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.weather
      - type: entities
        title: Room Lights
        show_header_toggle: true
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
      - type: plant-status
        entity: plant.window
      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - switch.bugzapper
          - switch.thunder
      - type: media-control
        entity: media_player.tv

  - id: lights
    title: All Lights
    icon: mdi:lightbulb
    cards:
      - type: entity-filter
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
        state_filter:
         - on
        card: 
          type: glance
          title: Lights that are On
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.dining
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_1
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_2
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_3
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.living_room
          -   type: glance
              entities: 
                - light.gold_lamp
          -   type: glance
              entities: 
                - light.crystal_lamp
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.bedroom
          -   type: glance
              entities: 
                - light.tall_lamp
          -   type: glance
              entities: 
                - light.reading_lamp
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.kitchen
          -   type: glance
              entities: 
                - light.sink_lightstrip
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.garage
          -   type: glance
              entities: 
                - light.hue_color_downlight_1
  - id: rover
    title: Rover
    icon: mdi:car
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            title: "Charge Level"
            entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
            severity:
              green: 20
              yellow: 0
              red: 90
          - type: glance
            entities:
              - sensor.tesla_model_3_5yj3e1ea8hf000718_range_sensor
      - id:
        type: entities
        entities: 
          - climate.tesla_model_3_5yj3e1ea8hf000718_hvac_climate_system
      - type: history-graph
        title: 'Car Temperature'
        entities:
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_temperature_sensor_inside
            name: Inside
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_temperature_sensor_outside
            name: Outside
      - type: entities
        show_header_toggle: false
        entities:
          - binary_sensor.tesla_model_3_5yj3e1ea8hf000718_charger_sensor
          - binary_sensor.tesla_model_3_5yj3e1ea8hf000718_parking_brake_sensor
          - sensor.tesla_model_3_5yj3e1ea8hf000718_mileage_sensor
          - group.rover
          - sensor.charger_watts
      - type: history-graph
        title: 'Car Energy'
        hours_to_show: 168
        entities:
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
            name: Battery Level
      - type: entities
        title: Charger Control
        show_header_toggle: false
        entities:
          - switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
          - switch.tesla_model_3_5yj3e1ea8hf000718_maxrange_switch
          - switch.teslacharger
      - type: entities
        show_header_toggle: false
        entities:
          - lock.tesla_model_3_5yj3e1ea8hf000718_door_lock
  - id: system
    title: System
    icon: mdi:server
    cards:
      - type: markdown
        title: 'System Links'
        content: > 
          - [Documentation](https://github.com/jeffglousher)
          
          - [Hass Configurator](https://www.glousher.com:3218/)
          
          - [Router](http://192.168.1.1) *LAN/VPN Access Only!*
          
          - [Netgear Orbi - Master](http://192.168.1.2) *LAN/VPN Access Only!*
          
          - [Netgear Orbi - Satellite](http://192.168.1.3) *LAN/VPN Access Only!*
          
          - [Portainer](http://192.168.1.51:9000/) *LAN/VPN Access Only!*
          
          - [PlantUML](http://192.168.1.51:8080) *LAN/VPN Access Only!*
          
          - [Chronograf](http://192.168.1.51:8888) *LAN/VPN Access Only!*
          
          - [ESXi](https://192.168.1.50/) *LAN/VPN Access Only!*
    
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.1539135661190
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - automation.turn_garage_light_off_again
          - automation.daily_lets_encrypt_renewal
          - automation.disable_outlet_when_rover_leaves_home
          - automation.do_at_sunrise
          - automation.do_at_sunset
          - automation.enable_outlet_when_rover_is_home
          - automation.html5_notification_click_action__open_door
          - automation.home_assistant_shutdown
          - automation.home_assistant_start
          - automation.set_gold_lamp_to_relax_when_soil_moisture_is_ok
          - automation.stop_charging_rover_on_a_weekendholiday
          - automation.stop_charging_rover_on_a_workday
          - automation.soil_moisture_is_low
          - automation.warning_for_upcoming_ssl_expiry
          - automation.do_a_bit_after_sunrise
          - automation.notify_when_rovers_is_not_at_home_and_start_charging