title: Estates
# Exclude entities from "Unused entities" view
excluded_entities:
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_locks
  - group.all_plants
  - group.all_scripts
  - group.all_switches
  - light.entertainment_area_1
  - device_tracker.tesla_model_3_5yj3e1ea8hf000718_location_tracker
  - device_tracker.b4e62ae90d29
  - device_tracker.404e36902186
  - device_tracker.android957114c2e834a0d6gloushercom
  - sensor.temperature
  - sensor.moisture
  - sensor.weather_icon
  - sensor.freebsd_router_bytes_received
  - sensor.freebsd_router_packets_received
  - sensor.freebsd_router_bytes_sent
  - sensor.freebsd_router_packets_sent
resources:
  - url: /local/toggle-lock-entity-row.js
    type: js
views:

  - id: overview
    title: Home Overview
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.weather
      - type: entities
        title: Room Lights
        show_header_toggle: false
        entities:
          - entity: light.bedroom
            type: custom:toggle-lock-entity-row
          - entity: light.dining
            type: custom:toggle-lock-entity-row
          - entity: light.garage
            type: custom:toggle-lock-entity-row
          - entity: light.kitchen
            type: custom:toggle-lock-entity-row
          - entity: light.living_room
            type: custom:toggle-lock-entity-row
      - type: plant-status
        entity: plant.window
      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - entity: switch.bugzapper
            type: custom:toggle-lock-entity-row
          - entity: switch.thunder
            type: custom:toggle-lock-entity-row
      - type: media-control
        entity: media_player.tv

  - id: lights
    title: All Lights
    icon: mdi:lightbulb
    cards:
      - type: entity-filter
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
        state_filter:
         - on
        card: 
          type: glance
          title: Lights that are On
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.living_room
          -   type: glance
              entities: 
                - light.gold_lamp
          -   type: glance
              entities: 
                - light.crystal_lamp
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.dining
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_1
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_2
          -   type: glance
              entities: 
                - light.hue_ambiance_spot_3
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.bedroom
          -   type: glance
              entities: 
                - light.tall_lamp
          -   type: glance
              entities: 
                - light.reading_lamp
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.kitchen
          -   type: glance
              entities: 
                - light.sink_lightstrip
        - type: vertical-stack
          cards:
          -   type: entity-button
              entity: light.garage
          -   type: glance
              entities: 
                - light.hue_color_downlight_1
      - type: entities
        entities:
          - entity: switch.flux
            name: Home Flux light:sun tracking
            type: custom:toggle-lock-entity-row
  - id: rover
    title: Rover
    icon: mdi:car
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            title: "Charge Level"
            entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
            severity:
              green: 20
              yellow: 0
              red: 90
          - type: glance
            entities:
              - sensor.tesla_model_3_5yj3e1ea8hf000718_range_sensor
      - id:
        type: entities
        entities: 
          - climate.tesla_model_3_5yj3e1ea8hf000718_hvac_climate_system
      - type: history-graph
        entities:
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_temperature_sensor_inside
            name: Inside Temperature
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_temperature_sensor_outside
            name: Outside Temperature
      - type: entities
        show_header_toggle: false
        entities:
          - group.rover
          - binary_sensor.tesla_model_3_5yj3e1ea8hf000718_parking_brake_sensor
          - sensor.tesla_model_3_5yj3e1ea8hf000718_mileage_sensor
          - binary_sensor.tesla_model_3_5yj3e1ea8hf000718_charger_sensor
          - sensor.charger_watts
      - type: history-graph
        hours_to_show: 168
        entities:
          - entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
            name: Battery Level
      - type: entities
        title: Charger Control
        show_header_toggle: false
        entities:
          - entity: switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
            type: custom:toggle-lock-entity-row
          - entity: switch.tesla_model_3_5yj3e1ea8hf000718_maxrange_switch
            type: custom:toggle-lock-entity-row
          - entity: switch.teslacharger
            type: custom:toggle-lock-entity-row
      - type: entities
        show_header_toggle: false
        entities:
          - lock.tesla_model_3_5yj3e1ea8hf000718_door_lock
  - id: weather
    title: Weather
    icon: mdi:weather-cloudy
    cards:
      - type: glance
        entities:
          - sensor.weather_temperature
          - sensor.weather_summary
          - sun.sun
          - sensor.moon
      - type: history-graph
        entities: 
          - entity: sensor.weather_dew_point
            name: Dew point
          - entity: sensor.weather_temperature
            name: Temperature
          - entity: sensor.weather_apparent_temperature
            name: Apparent temperature
          - entity: sensor.weather_overnight_low_temperature
            name: Overnight low
          - entity: sensor.weather_overnight_low_apparent_temperature
            name: Overnight apparent low
          - entity: sensor.weather_daytime_high_temperature
            name: Daytime high
          - entity: sensor.weather_daytime_high_apparent_temperature
            name: Daytime apparent high
          - entity: sensor.weather_humidity
            name: Humidity
          - entity: sensor.weather_precip_probability
            name: Precipitation probability
          - entity: sensor.weather_cloud_coverage
            name: Cloud coverag
          - entity: sensor.humidity
            name: Indoor humidity
      - type: glance
        entities:
          - sensor.weather_daily_max_precip_intensity
          - sensor.weather_moon_phase
          - sensor.weather_nearest_storm_distance
          - sensor.weather_precip_intensity
          - sensor.weather_ozone
          - sensor.weather_uv_index
          - sensor.weather_precip
          - sensor.weather_precip_accumulation
          - sensor.weather_pressure
          - sensor.weather_visibility
          - sensor.weather_wind_bearing
          - sensor.weather_wind_speed
      - type: weather-forecast
        entity: weather.weather
  - id: system
    title: System
    icon: mdi:server
    cards:
      - type: glance
        entities:
          - binary_sensor.workday_sensor
          - sensor.disk_free_home
          - sensor.disk_use_percent_home
          - sensor.ssl_certificate_expiry
          - sensor.load_1m
          - sensor.uptime
          - sensor.memory_free
          - sensor.network_in_enp2s1
          - sensor.network_out_enp2s1
      - type: history-graph
        hours_to_show: 48
        entities:
          - entity: sensor.freebsd_router_kbytesec_sent
          - entity: sensor.freebsd_router_kbytesec_received
          - entity: sensor.freebsd_router_packetssec_sent
          - entity: sensor.freebsd_router_packetssec_received
          - entity: sensor.memory_use_percent
          - entity: sensor.processor_use
          
      - type: markdown
        title: 'System Links'
        content: > 
          - [Documentation](https://github.com/jeffglousher)
          
          - [Hass Configurator](https://www.glousher.com:3218/)
          
          - [Router](http://192.168.1.1) *LAN/VPN Access Only!*
          
          - [Netgear Orbi - Master](http://192.168.1.2) *LAN/VPN Access Only!*
          
          - [Netgear Orbi - Satellite](http://192.168.1.3) *LAN/VPN Access Only!*
          
          - [Portainer](http://192.168.1.51:9000/) *LAN/VPN Access Only!*
          
          - [PlantUML](http://192.168.1.51:8080) *LAN/VPN Access Only!*
          
          - [Chronograf](http://192.168.1.51:8888) *LAN/VPN Access Only!*
          
          - [ESXi](https://192.168.1.50/) *LAN/VPN Access Only!*
    
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities:
          - script.notify_jeff_with_feedback
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - automation.turn_garage_light_off_again
          - automation.daily_lets_encrypt_renewal
          - automation.disable_outlet_when_rover_leaves_home
          - automation.do_at_sunrise
          - automation.do_at_sunset
          - automation.enable_outlet_when_rover_is_home
          - automation.html5_notification_click_action__open_door
          - automation.home_assistant_shutdown
          - automation.home_assistant_start
          - automation.set_gold_lamp_to_relax_when_soil_moisture_is_ok
          - automation.stop_charging_rover_on_a_weekendholiday
          - automation.stop_charging_rover_on_a_workday
          - automation.soil_moisture_is_low
          - automation.warning_for_upcoming_ssl_expiry
          - automation.do_a_bit_after_sunrise
          - automation.notify_when_rovers_is_not_at_home_and_start_charging