title: Estates
views:
  - id: overview
    title: Home Overview
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.weather
      - type: plant-status
        entity: plant.window
      - type: entities
        title: Room Lights
        show_header_toggle: true
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - switch.bugzapper
          - switch.thunder
      - type: media-control
        entity: media_player.tv
  - id: lights
    title: All Lights
    icon: mdi:lightbulb
    cards:
      - type: entity-filter
        entities:
          - light.bedroom
          - light.dining
          - light.garage
          - light.kitchen
          - light.living_room
        state_filter:
         - on
        card: 
          type: glance
          title: Lights that are On
  - id: rover
    title: Rover
    icon: mdi:car
    cards:
      - id:
        type: thermostat
        entity: climate.tesla_model_3_5yj3e1ea8hf000718_hvac_climate_system
      - type: entities
        title: all locks
        show_header_toggle: true
        entities:
          - lock.tesla_model_3_5yj3e1ea8hf000718_door_lock
      - type: entities
        title: all switches
        show_header_toggle: false
        entities:
          - switch.tesla_model_3_5yj3e1ea8hf000718_charger_switch
          - switch.tesla_model_3_5yj3e1ea8hf000718_maxrange_switch
          - switch.teslacharger
      - type: sensor
        entity: sensor.tesla_model_3_5yj3e1ea8hf000718_battery_sensor
        name: Battery
        height: 75
        line_color: "#3498db"
  - id: system
    title: System
    icon: mdi:server
    cards:
      - type: entities
        title: all scripts
        show_header_toggle: false
        entities:
          - script.1539135661190
      - type: entities
        title: all automations
        show_header_toggle: false
        entities:
          - automation.daily_lets_encrypt_renewal
          - automation.disable_outlet_when_rover_leaves_home
          - automation.do_at_sunrise
          - automation.do_at_sunset
          - automation.enable_outlet_when_rover_is_home
          - automation.html5_notification_click_action__open_door
          - automation.home_assistant_shutdown
          - automation.home_assistant_start
          - automation.set_gold_lamp_to_relax_when_soil_moisture_is_ok
          - automation.stop_charging_rover_on_a_weekendholiday
          - automation.stop_charging_rover_on_a_workday
          - automation.turn_gold_lamp_blue_when_soil_moisture_is_low
          - automation.warning_for_upcoming_ssl_expiry